### ISSUE TITLE
Update NMFS pkgdown template

### ISSUE THREAD

**Issue by k-doering-NOAA** [noaa-fisheries-integrated-toolbox/FIT-committee#47]
This entails editing the [NOAA themed pkgdown blog post](https://noaa-fisheries-integrated-toolbox.github.io/resources/noaa%20resources/NOAA-pkgdown/).

Here is the [pkgdown template repo](https://nmfs-fish-tools.github.io/pkgdownTemplate/)

**Comment by MargaretSiple-NOAA** [comment]
We moved this repo over to NMFS Open Sci (Eli, Bai and Christine all agreed this was a good place to put it). And Kathryn and I edited the pkgdown blog post on the FIT website. My next step will be to test the instructions with an example R package, and then I think this task will be complete!

**Comment by MargaretSiple-NOAA** [comment]
I tested the tutorial with an experimental package of my own ([palettehelper](https://margaretsiple-noaa.github.io/palettehelper/)) and it worked great! I started with a pre-existing package repo, as we discussed. 

So the final assessment of this was; we moved the repo over to NMFS Open Sci, and revised the pkgdown blog post for the FIT blog. Going to close this issue because I think we are finished!

**Comment by eeholmes** [comment]
@MargaretSiple-NOAA  I was mostly able to follow the blog to add pkgdown to someone's site with the following notes

* I had to already know what to do re GitHub Action to follow those instructions.

* The footer image is huge for some reason.



![Image](https://github.com/noaa-fisheries-integrated-toolbox/FIT-committee/assets/2545978/9d21306a-a76a-4e8f-ab60-0f1bc018e3d4)

**Comment by eeholmes** [comment]
Also there is some weirdness in the css. Look at the side navbar



![Image](https://github.com/noaa-fisheries-integrated-toolbox/FIT-committee/assets/2545978/89836f0c-bab8-4aa5-9136-a05cb4d49454)

**Comment by MargaretSiple-NOAA** [comment]
Thanks Eli, and yikes re: that icon size! That's a drive-thru icon. I did some experimenting with adding a hex sticker and can add that to the instructions. For a little more elaboration on the GitHub Actions part, did you use the {usethis} way, or did you use it without {usethis}? 

I'll see what's up with the css. I just noticed that too. I hadn't looked at the references page yet. I think I just inherited the css from the previous version so may have to do some digging.

**Comment by eeholmes** [comment]
I put in a PR to fix the image size. I'd forgotten that I'd fixed this some time ago in my pkgdown template but that fix didn't get migrated upward.

**Comment by eeholmes** [comment]
Re logo:

* Add logo to man/figures/logo.png 
* Then add the top of your README.md like so
```
# yourpackagename <img src="man/figures/logo.png" align="right" />
```
pkgdown will handle the rest including creating a favicon for you. Just make sure to call your logo `logo.png`

**Comment by eeholmes** [comment]
Re GitHub Action, I used the gh4actions package but I knew what I was doing. It would be good to watch someone try to apply the instructions if they have no or limited experience with GH Actions.

**Comment by k-doering-NOAA** [comment]
> Thanks Eli, and yikes re: that icon size! That's a drive-thru icon. I did some experimenting with adding a hex sticker and can add that to the instructions. For a little more elaboration on the GitHub Actions part, did you use the {usethis} way, or did you use it without {usethis}?
> 
> I'll see what's up with the css. I just noticed that too. I hadn't looked at the references page yet. I think I just inherited the css from the previous version so may have to do some digging.

@MargaretSiple-NOAA do you think we still need to make edits to the blog post? If so, feel free to put coworking time on my calendar so we can finish it up!

@eeholmes , if you have thoughts on additional documentation need for ghactions, please feel free to make changes on the [blog post](https://github.com/noaa-fisheries-integrated-toolbox/resources/edit/main/_posts/2024-02-20-NOAA-pkgdown.md) and submit it as a PR. I cannot tell what is missing, but if someone from the FIT committee with limited ghactions experience could volunteer to test out the blog post, I think that could be helpful!

**Comment by eeholmes** [comment]
Re GA documentation, Let's ask someone inexperienced try to follow the instructions at the next FIT meeting.

**Comment by MargaretSiple-NOAA** [comment]
So sorry for the delay on this you two. I plan to do this work this week. We will likely need to edit the blog post but I'll take a look and see what we should revise. I had no trouble following the instructions and don't frequently use GHA, but I can revisit.

**Comment by k-doering-NOAA** [comment]
@Bai-Li-NOAA just fixed the CSS issue here: https://github.com/nmfs-fish-tools/nmfspalette/pull/31

I think it should auto update if people are refering to the nmfspalette css file.

As for gha, I think it is fine to leave it as-is if @MargaretSiple-NOAA is not a frequent GHA user and found the instructions possible to follow. I'm going to close this, but feel free to reopen if there are things to revisit.

**Comment by MargaretSiple-NOAA** [comment]
Thank you Kathryn! Yes if the css change fixed the menu issue, that's probably the most glaring issue. I am not a frequent GHA user and was able to follow the instructions, but can run through them again for thoroughness. If I find anything crazy, I'll reopen but I think they're okay. 

I have a fork where I'm adding instructions for adding a logo / favicon and will make a pull request.

**Comment by k-doering-NOAA** [comment]
@MargaretSiple-NOAA yes, it will solve the menu issue.

Thanks for working on the instructions for adding a logo! I think it's ok to leave the github actions instructions as-is.
