### ISSUE TITLE
Consider how a FIT R universe page can supplement the FIT website.

### ISSUE THREAD

**Issue by k-doering-NOAA** [noaa-fisheries-integrated-toolbox/FIT-committee#58]

**Comment by k-doering-NOAA** [comment]
Some information about how [other communities are using R universe](https://ropensci.org/blog/2023/11/06/r-universe-stars-finale/)

**Comment by eeholmes** [comment]
We use it for our time-series packages: https://atsa-es.r-universe.dev/packages. So easy to set up and make much much easier for people to install your GitHub packages esp if they include C++ code (e.g. TMB) because they don't have to build them. Works like installing from CRAN.

**Comment by k-doering-NOAA** [comment]
We do have this [experimental FIT one](https://noaa-fisheries-integrated-toolbox.r-universe.dev/packages).

I think the other advantages is you need the whole r-tools chain for github pkgs with c++ code if you install from r universe.

**Comment by k-doering-NOAA** [comment]
Recent value added: devtools::install_github() isn't working on NOAA laptops, and pak::pak() required the package build tool chain. Installation from R universe does not, so the user was able to install from R universe as a "quick fix" way to get the package nmfspalette, which is not on CRAN. 

R universe can be a helpful tool for users and developers of the toolbox; We could provide instructions on how to install using R universe on the R package pages?

**Comment by k-doering-NOAA** [comment]
I think there are some clear uses of R universe that could be helpful. I think when developing the FY25 plan, we can consider specific action items based on what we know about R universe. For example:
- Committing to maintain an R universe for the FIT and advertise it(we have one, but it is not well advertised)
- Add install instructions using R universe to all of the FIT R packages
