### ISSUE TITLE
Keep tabs on open science developments, ensuring FIT complements other open science efforts

### ISSUE THREAD

**Issue by k-doering-NOAA** [noaa-fisheries-integrated-toolbox/FIT-committee#60]

**Comment by k-doering-NOAA** [comment]
Scheduled time with Eli to discuss this.

**Comment by MargaretSiple-NOAA** [comment]
I may not be able to do anything major on this until August when I return from the survey, but I will keep tabs on it.

**Comment by k-doering-NOAA** [comment]
@eeholmes and I met today to check on this! In general, we feel that we aren't duplicating effort between FIT and NMFS-opensci, which is fantastic! To some extent, this happens naturally because many FIT committee members have also been involved as openscapes mentors (assigned to this issue).

Things to think about for the future:
- FIT could reach out to NMFS-opensci if there are specific training or events if we would like to run
- FIT can outreach to the NMFS-opensci/NMFS openscapes community as makes sense to.

I don't think there is much action to take right now for this FY, so I'm going to close this issue.
