### ISSUE TITLE
one pager on FY 23 accomplishments and FY24 strategic plan

### ISSUE THREAD

**Issue by k-doering-NOAA** [noaa-fisheries-integrated-toolbox/FIT-committee#62]
To share FIT updates with the science board.

**Comment by k-doering-NOAA** [comment]
Thanks to @mollystevens-noaa for being willing to review the first draft!

I'll share with everyone in the January update, but if anyone would like an earlier look to provide comments, let me know and I can share the link.

**Comment by mollystevens-noaa** [comment]
I think it looks great, @k-doering-NOAA !  I duplicated the [one-pager on Canva](https://www.canva.com/design/DAF4H7QQgpI/ySjd8Naim8FmZ_uUE7t-GQ/edit) and edited the second page for you to accept/reject changes I made.

**Comment by k-doering-NOAA** [comment]
Thanks, Molly! I created a [pdf version to comment on](https://drive.google.com/file/d/1KjKio1BFLuagqOkFbElPTL_8DN1ikN0E/view?usp=sharing) in our shared google drive, if anyone else would like to provide feedback ahead of the January update email.

**Comment by k-doering-NOAA** [comment]
Committee will comment through 1/19, Rick will share with science board on 1/24
